### ISSUE TITLE
Line-Sweep Ambient Obscurance Optimization?

### ISSUE THREAD

**Issue by kkimdev** [GameTechDev/ASSAO#5] opened 2017-01-13 08:49 UTC
Line-Sweep Ambient Obscurance ( http://wili.cc/research/lsao/ ) outperforms HBAO by x10~x20.

Is this  applicable?

**Comment by fstrugar** [comment] 2017-01-16 12:28
Looks like it might be, but it's really hard to tell without trying it out side by side, and in motion. They've provided the source code which is great but I don't have a linux machine set up to try it out so I'll put it on "todo" list. 

If anyone wants to help porting it into ASSAO DX11 sample, all the boilerplate code is already there in ExternalSSAOWrapper.h/cpp!

**Comment by fstrugar** [comment] 2017-03-06 16:42
I've looked at this a bit more and did a quick dirty prototype and although it seems to work as intended, I don't see a clear path to resolving the line-sweep gradient artifacts (it's actually very noticeable in the original video provided with the paper, at around 48s - https://youtu.be/Cz7BBU3ypR0?t=48s).
So I'll put this on hold but, again, if anyone wants to do a proper port, it would be interesting to compare.

**Closed as completed** 2017-03-06 16:43 UTC
Labels: help wanted

**Comment by kkimdev** [comment] 2017-03-06 18:16
I see.  Thanks for the investigation!!
